<?php

require_once dirname(__FILE__) . '/../../classes/IdTag.php';

/**
 * Test class for IdTag.
 * Generated by PHPUnit on 2012-06-28 at 17:11:50.
 */
class IdTagTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var IdTag
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp ()
    {
        $this->object = new IdTag;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown ()
    {

    }

    public function testLoadTag ()
    {

    }

    public function testSaveTag ()
    {

    }
    
    public function testGetTag ()
    {

    }

    public function testSetTag ()
    {

    }

    public function testGetAllTags ()
    {

    }

    public function testGetTagVersion()
    {

    }
}

?>
